### ISSUE TITLE
vertex data changed every frame, but lost last triangles 

### ISSUE THREAD

**Issue by masterhou** [fincs/citro3d#10]
I write a metaball. The vertex data will be changed every frame, some hole in holes, like screenshot.
when I stop change vertex data, it ok.
C3D_DrawArrays(GPU_TRIANGLES, 0, metaballs->numVertices);
I think numVertices is not upload correct number, less. Then I add some, will better.
C3D_DrawArrays(GPU_TRIANGLES, 0, metaballs->numVertices+120);
![wechat_1465712036](https://cloud.githubusercontent.com/assets/567426/15989393/f2261b8e-30a7-11e6-9344-565fdb31da42.jpeg)

**Comment by Cruel** [comment]
Will need a lot more example code to help recreate.

**Comment by masterhou** [comment]
https://github.com/masterhou/Blobs.git

**Comment by mtheall** [comment]
The screenshot appears like you are intersecting the near clip plane.

**Comment by masterhou** [comment]
Not intersecting the near clip plane.
When stop changed vertex and rotate, then holes are disappeared.

**Comment by fincs** [comment]
Did anybody reproduce similar issues? I suspect this is user error.

**Comment by fincs** [comment]
Closing due to lack of information and interest. If anyone experiences a similar problem, please open a new issue.
