### ISSUE TITLE
Preparing graphics and textures

### ISSUE THREAD

**Issue by Chrs2021** [fincs/citro3d#2]
hi what do you use to prepare the textures in the examples shown?

**Comment by fincs** [comment]
Currently there's no standard texture conversion tool. For the moment you can either use PNG (take a look at the [gpusprites example](https://github.com/devkitPro/3ds-examples/blob/master/graphics/gpu/gpusprites/source/main.c#L126)), or [smea's conversion script](https://github.com/smealum/portal3DS/blob/master/tools/texconv.py).
