### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by UselessMnemonic** [fincs/citro3d#30]
This enum...
typedef enum
{
GPU_RGBA8 = 0x0, ///< 8-bit Red + 8-bit Green + 8-bit Blue + 8-bit Alpha
GPU_RGB8 = 0x1, ///< 8-bit Red + 8-bit Green + 8-bit Blue
GPU_RGBA5551 = 0x2, ///< 5-bit Red + 5-bit Green + 5-bit Blue + 1-bit Alpha
GPU_RGB565 = 0x3, ///< 5-bit Red + 6-bit Green + 5-bit Blue
GPU_RGBA4 = 0x4, ///< 4-bit Red + 4-bit Green + 4-bit Blue + 4-bit Alpha
GPU_LA8 = 0x5, ///< 8-bit Luminance + 8-bit Alpha
GPU_HILO8 = 0x6, ///< 8-bit Hi + 8-bit Lo
GPU_L8 = 0x7, ///< 8-bit Luminance
GPU_A8 = 0x8, ///< 8-bit Alpha
GPU_LA4 = 0x9, ///< 4-bit Luminance + 4-bit Alpha
GPU_L4 = 0xA, ///< 4-bit Luminance
GPU_ETC1 = 0xB, ///< ETC1 texture compression
GPU_ETC1A4 = 0xC, ///< ETC1 texture compression + 4-bit Alpha
} GPU_TEXCOLOR;

...does not define GPU_A4...

which causes this error...
c:/ ... /citro3d/source/texture.c:25:8: error: 'GPU_A4' undeclared (first use in this function)
case GPU_A4:
^

**Comment by Cruel** [comment]
You need latest ctrulib from git, [it's define there](https://github.com/smealum/ctrulib/blob/3501efd7e5301ac00fa08eed5ee9b327e506c667/libctru/include/3ds/gpu/enums.h#L62).
