### ISSUE TITLE
Texture init fails when default data pointer is not null

### ISSUE THREAD

**Issue by Cruel** [fincs/citro3d#31]
I'm referring to [this line](https://github.com/fincs/citro3d/blob/2054a9230b23fd2ca666c7b6818433c695d71afe/source/texture.c#L40). This is what I expect to work:

```C
C3D_Tex tex;
C3D_TexInit(&tex, 64, 64, GPU_RGB8);
```

However it will fail depending on the initial value of the data pointer. At the moment, I just use `tex.data = NULL;` before it. Perhaps it's better to trust the user won't initialize multiple times instead of requiring the struct to be zero'd?

**Comment by fincs** [comment]
Noted. Currently you are supposed to memset C3D_Tex structures on the stack before initializing them.

**Comment by fincs** [comment]
See 033c600.
