### ISSUE TITLE
Exception: STATUS_ACCESS_VIOLATION in appveyor

### ISSUE THREAD

**Issue by OctoNezd** [fincs/citro3d#32]
See [this](https://ci.appveyor.com/project/OctoNezd/ntrdbi/build/NIGHTLY-appveyor-support-31#L151)

**Comment by fincs** [comment]
This is not a citro3d issue, it is an issue with your AppVeyor build script. Please try to use a stock toolchain with stock tools and libraries as distributed by devkitPro; otherwise we cannot offer support. Also it may help to use a Linux build box instead of a Windows one.
