### ISSUE TITLE
Build issues with updated devkitpro install AND latest ctrulib installed

### ISSUE THREAD

**Issue by urherenow** [fincs/citro3d#33]
arm-none-eabi-gcc -MMD -MP -MF /c/Projects/citro3d/build/attribs.d -g -Wall -Wextra -Werror -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -I/c/Projects/citro3d/include -I/c/devkitPro/libctru/include -I/c/Projects/citro3d/build -DARM11 -D_3DS -DCITRO3D_BUILD -c /c/Projects/citro3d/source/attribs.c -o attribs.o
base.c
arm-none-eabi-gcc -MMD -MP -MF /c/Projects/citro3d/build/base.d -g -Wall -Wextra -Werror -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -I/c/Projects/citro3d/include -I/c/devkitPro/libctru/include -I/c/Projects/citro3d/build -DARM11 -D_3DS -DCITRO3D_BUILD -c /c/Projects/citro3d/source/base.c -o base.o
c:/Projects/citro3d/source/base.c: In function 'C3Di_FinalizeFrame':
c:/Projects/citro3d/source/base.c:275:2: error: 'GPUCMD_Finalize' is deprecated [-Werror=deprecated-declarations]
  GPUCMD_Finalize();
  ^~~~~~~~~~~~~~~
In file included from c:/devkitPro/libctru/include/3ds.h:69:0,
                 from c:/Projects/citro3d/include/c3d/types.h:3,
                 from c:/Projects/citro3d/include/c3d/attribs.h:2,
                 from c:/Projects/citro3d/source/internal.h:2,
                 from c:/Projects/citro3d/source/base.c:1:
c:/devkitPro/libctru/include/3ds/gpu/gpu.h:81:17: note: declared here
 DEPRECATED void GPUCMD_Finalize(void);
                 ^~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[1]: *** [base.o] Error 1
make: *** [build] Error 2

**Comment by fincs** [comment]
There is no such thing as a "devkitPro" install; what you refer to is devkitARM and libctru. Regardless of that, bleeding edge versions of tools and libraries are not guaranteed to work since they often rely on specific configurations and versions that only exist in developers' machines. Please stick to stable releases if you want software that is guaranteed to work.

(Also, you may be interested in the [next](https://github.com/fincs/citro3d/tree/next) branch)

**Comment by urherenow** [comment]
I used the official devkitPro installer which installs more than just devkitARM. Thanks for the link though.

**Comment by fincs** [comment]
Stable versions of citro3d are also distributed and installed using devkitProUpdater.
