### ISSUE TITLE
C3D_SafeDisplayTransfer causes freezes in "next" branch.

### ISSUE THREAD

**Issue by Steveice10** [fincs/citro3d#34]
Using C3D_SafeDisplayTransfer seems to randomly cause my app, FBI, to completely lock up when built against the "next" branch of citro3d. It is used at [this](https://github.com/Steveice10/FBI/blob/master/source/core/screen.c#L401) point when loading textures, The issue can be observed by refreshing the title list repeatedly until it occurs from the loading of icon textures.

Testing was done on an N3DS running 11.4.0-37U with Luma3DS v8.1. This issue does not occur when built against the master branch of citro3d.

**Comment by fincs** [comment]
Thank you for reporting. I will investigate.

**Comment by fincs** [comment]
I've looked a bit at the FBI source code, and noticed that you are using the safe transfer functions in a separate thread. These functions have never been intended to be used outside the main (graphics) thread. Multiple threads trying to submit GX commands at the same time has always been a recipe for disaster. As an alternative you may want to instead convert the tiles in software.

**Comment by Steveice10** [comment]
Ah, I didn't even think about that. Thanks for the info, working on a solution now.
