### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by Magicrafter13** [fincs/citro3d#37]
I've tried the release and the latest commit, they both fail with the same errors:

C:\Users\scuba\Downloads\citro3d-1.3.0>make install
attribs.c
arm-none-eabi-gcc -MMD -MP -MF /c/Users/scuba/Downloads/citro3d-1.3.0/release/attribs.d -g -Wall -Werror -mword-relocations -ffunction-sections -fdata-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -DNDEBUG=1 -O2 -fomit-frame-pointer -I/c/Users/scuba/Downloads/citro3d-1.3.0/include -I/c/devkitPro/libctru/include -I. -DARM11 -D_3DS -DCITRO3D_BUILD -c /c/Users/scuba/Downloads/citro3d-1.3.0/source/attribs.c -o attribs.o
In file included from c:/Users/scuba/Downloads/citro3d-1.3.0/source/internal.h:8:0,
                 from c:/Users/scuba/Downloads/citro3d-1.3.0/source/attribs.c:1:
c:/Users/scuba/Downloads/citro3d-1.3.0/include/c3d/fog.h:18:21: error: unknown type name 'GPU_FOGMODE'
 void C3D_FogGasMode(GPU_FOGMODE fogMode, GPU_GASMODE gasMode, bool zFlip);
                     ^~~~~~~~~~~
c:/Users/scuba/Downloads/citro3d-1.3.0/include/c3d/fog.h:18:42: error: unknown type name 'GPU_GASMODE'
 void C3D_FogGasMode(GPU_FOGMODE fogMode, GPU_GASMODE gasMode, bool zFlip);
                                          ^~~~~~~~~~~
In file included from c:/Users/scuba/Downloads/citro3d-1.3.0/source/attribs.c:1:0:
c:/Users/scuba/Downloads/citro3d-1.3.0/source/internal.h:33:2: error: unknown type name 'gxCmdQueue_s'
  gxCmdQueue_s gxQueue;
  ^~~~~~~~~~~~
make[1]: *** [attribs.o] Error 1
make: *** [lib/libcitro3d.a] Error 2

**Comment by fincs** [comment]
Upgrade libctru.
