### ISSUE TITLE
Multiple textures point to the same buffer

### ISSUE THREAD

**Issue by Steveice10** [fincs/citro3d#38]
I got a report of an issue in FBI where multiple titles will show the same icon. Adding some debug output revealed that multiple different textures had the same data pointer. Note that I haven't been able to reproduce this myself, and am unsure under what conditions this occurs.

Reverting to ctrulib 1.2.0 and citro3d 1.2.0 made this issue go away; it only started after upgrading to the latest of both.

Screenshots of debug output (format: texture id, data pointer, width x height (power of 2 width x power of 2 height)): http://gbatemp.net/threads/release-fbi-open-source-cia-installer.386433/page-195#post-7517517

Code allocating texture: https://github.com/Steveice10/FBI/blob/master/source/core/screen.c#L352

**Comment by Jerry-Shaw** [comment]
Yep, met the same issue here. The icons may be the same between up and down titles, sometimes even changed to be the same when listing title action not fully finished.
I was just ready to put a new issue in FBI, but suddenly saw you posted it here.

**Comment by Steveice10** [comment]
I've actually identified a possible cause on my end - will reopen if it turns out to not be the issue.

**Comment by fincs** [comment]
I suspect improper texture memory lifetime management on behalf of the user.

**Comment by Steveice10** [comment]
It did turn out to be a lifetime management problem, but not in that way.

My code relies on the data field being NULL to check whether or not a texture instance is valid. Previously, citro3d changed it to NULL in C3D_TexDelete, however it no longer does so. I encountered and fixed this before by manually setting it to NULL when redefining a texture's size and/or format, but forgot to also manually set it to NULL when unloading a texture.
