### ISSUE TITLE
Off screen Target Corruption

### ISSUE THREAD

**Issue by TurtleP** [fincs/citro3d#41]
I've come across a few other issues since I asked about how to make these. If I make the texture to render to in RAM there's very few missing spots of pixels in the first one, but subsequent ones may not render everything properly (missing pixels).

Placing the texture inside VRAM causes heavy garbage to be generated (and in some cases, VRAM corruption or something since I see home menu graphics appear).

I'm not sure what I'm doing wrong.. I start the frame, draw on the target, do the Mtx4x4 on the projection and after this is done, call end frame. Any ideas to fix this?

**Comment by fincs** [comment]
It would be nice if you posted some code that showed this problem. I have a suspicion it might be cache-related.

**Comment by TurtleP** [comment]
I apologize, but I wasn't on my desktop when I posted this and had its GPU have an issue to solve this morning. Let me get the code for you real quick:

```cpp
//canvas.cpp
const char * Canvas::Init(int width, int height)
{
this->width = width;
this->height = height;

this->texture = new love::Image();
this->texture->BasicInit(width, height);

this->target = new love::CRenderTarget(this->texture, this->texture->NextPow2(width), this->texture->NextPow2(height));

return nullptr;
}

//Image.cpp
void Image::BasicInit(int width, int height)
{
this->texture = new C3D_Tex();
this->width = width;
this->height = height;

C3D_TexInit(this->texture, this->NextPow2(width), this->NextPow2(height), GPU_RGBA8);

C3D_TexSetFilter(this->texture, magFilter, minFilter);

C3D_TexSetWrap(this->texture, GPU_CLAMP_TO_BORDER, GPU_CLAMP_TO_BORDER);
}

//Graphics.cpp
int Graphics::SetCanvas(lua_State * L)
{
if (!lua_isnoneornil(L, 1))
{	
Canvas * self = (Canvas *)luaobj_checkudata(L, 1, LUAOBJ_TYPE_CANVAS);

if (self->GetTarget()->GetTarget() == nullptr)
return 0;

//resetPool();

C3D_FrameBegin(C3D_FRAME_SYNCDRAW);

C3D_FrameDrawOn(self->GetTarget()->GetTarget());

C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, projection_desc, self->GetProjection());

lastCanvas = self;
}
else
{
if (lastCanvas != nullptr)
C3D_FrameEnd(0);
}

return 0;
}
```

**Comment by TurtleP** [comment]
Sorry to bug you, but has there been any progress on finding the cause?
