### ISSUE TITLE
example not working and help needed

### ISSUE THREAD

**Issue by Magicrafter13** [fincs/citro3d#45]
The example program compiles with errors, and I assume this is due to it being outdated compared to citro3d itself. And because of this, I am stuck, as I was trying to learn how to use citro3d.

Seriously though, if the people of the 3ds homebrew scene are so adamant about using citro3d instead of things like pp2d sf2d etc, then there needs to be a way to learn how to use it. @

**Comment by fincs** [comment]
The example programs were updated at the same time the latest citro3d was released. I think you don't have an up-to-date install. If you haven't already, use the new pacman-based installation procedure to make sure you have the latest version of everything (including 3ds-examples).

There's also a brand new library called citro2d that, as the name implies, is specifically designed to make 2D graphics programming easier (but not any less efficient!). This lib has full Doxygen documentation.

**Comment by Magicrafter13** [comment]
I'll try citro2d, though I have to ask, what the hell is pacman (in this context anyway).

**Comment by fincs** [comment]
It's a package manager we have adopted for the purposes of distributing the toolchains, libraries and others. Please refer to this:

https://devkitpro.org/viewtopic.php?f=13&t=8702&p=15914
https://devkitpro.org/viewtopic.php?f=13&t=8711

**Comment by Magicrafter13** [comment]
Hey fincs. Sorry, I'm confused. Is pacman a replacement for 'make install'?
I do have pacman installed, as I can run the command, but I don't really get what it's for. If it helps at all, I'm on Windows.
