### ISSUE TITLE
text3ds.c fails when attempting to 'make install'

### ISSUE THREAD

**Issue by pedro-etsi** [fincs/citro3d#46]
So this is what I got when I run 'make install'

![captura de pantalla de 2018-07-18 14-46-09](https://user-images.githubusercontent.com/35919204/42882644-989297b6-8a99-11e8-9df1-a315e289b3b7.png)

**Comment by mtheall** [comment]
Update libctru

**Comment by WinterMute** [comment]
We recommend using [pacman](https://devkitpro.org/wiki/devkitPro_pacman) to keep things up to date rather than attempting to compile everything from source unless you intend to contribute.
