### ISSUE TITLE
Question about BufInfo_Add() from C3D

### ISSUE THREAD

**Issue by Reon-Fourie** [fincs/citro3d#47]
Hi there 
So I'm making a Minecraft like voxel engine for the Nintendo 3DS and I know that it's and old console but still fun to program. Anyway after implementing a chunk mesh building system, I notices that some of the vertices don't get drawn and I'm suspecting that it could have something to do with the u64 permutation value which is the las argument of the BuffInfoAdd function. I'm not sure exactly what that value is. ATM it is set to 0x210 (528) which is a random value i found in one of the examples. So my question is what exactly is this value and how to I determine what to make it? 

Thanks for the time taken to answer my question

**Comment by fincs** [comment]
GitHub issues are not a support forum, they are for reporting issues with the repo (i.e. bugs). You might want to drop in at #3dsdev (@ EFnet).

Fyi the permutation specifies the order in which the attributes are stored in the buffer, LSB first. So 0x210 indicates attributes 0, 1 & 2.

**Comment by Reon-Fourie** [comment]
Thanks alot!
