### ISSUE TITLE
Uploading of the Reflective Red LUT not happening, plus a question....

### ISSUE THREAD

**Issue by DiscostewSM** [fincs/citro3d#5]
On line 91 of the lightenv.c file is a for-loop that counts upward until it reaches 5, then exits. This currently prevents the reflective red LUT from being uploaded because its index is 5. A change to **6** should fix this (as was done for the typo fix of the Nov 8, 2015 commit in a similar situation).

And regarding reflective RGB, there was a test done some time ago that StapleButter (and perhaps you?) were working on to utilize this for a special form of texture. An old project from Nov 4th given to me included a compiled 3dsx that works on Ninjhax 1.1b, showing a 4-color-per-side cube, but doesn't work on Ninjhax 2.6 gamma, which has a completely black cube. Building with the newest libraries (including this with a change tested for reflective red), results in this same black cube for all versions of Ninjhax, including 1.1b. Think we can talk about what's going on?

**Comment by fincs** [comment]
> This currently prevents the reflective red LUT from being uploaded because its index is 5.

Whoops. I'll fix this.

> Think we can talk about what's going on?

The test was done by StapleButter. It'd be nice if you posted the code somewhere.

**Comment by DiscostewSM** [comment]
I'll post it tonight if I have the time (and if I remember). I tried contacting you with the email I dug up from GitHub about this very project (which I attached the code), but I guess you either don't use that email anymore or have never used it.

**Comment by fincs** [comment]
I barely check my email address, it's mostly there so that I can register in various websites. Just checked the inbox, and indeed there is the zip with the source code.

**Comment by DiscostewSM** [comment]
Thanks for fixing the first problem. Would you happen to know anything about the second problem that is described?

**Comment by fincs** [comment]
After some tweaking, I did manage to compile it with latest tools, but all I got was a black square. I'm also puzzled by this.

**Comment by DiscostewSM** [comment]
Same here, but I did find that if I set all LUT entries of a color component to something > 0, then the cube would display as that color. Be aware that the project does use an altered version of the LightLUT_FromFunc subroutine to achieve this.

If you want, we can discuss this elsewhere, perhaps even the 4ds-dev site that StapleButter has.
