### ISSUE TITLE
Missing texture formats

### ISSUE THREAD

**Issue by DiscostewSM** [fincs/citro3d#6]
Currently, these are the valid formats used in citro3D within texture.c

RGBA8, RGB8, RGBA5551, RGB565, RGBA4

It is missing the others like L8 (this particular one has a size of 1). This is not important because people might use these other formats, but because this issue is linked to the 2nd part of the last issue I brought up (which currently displays a black cube). Added L8 as a valid format with a return value of 1, then made alterations to the other project, and now it's displaying what it should.

**Comment by fincs** [comment]
Thanks for spotting this, I'm about to fix it.
